### ISSUE TITLE
Problemas con la carga del proyecto.

### ISSUE THREAD

**Issue by AndriyHaydychuk** [cinder92/cordova-music-app#4]
Hola, después de instalar todo lo solicitado para el correcto funcionamiento del proyecto, al intentar arrancarlo se queda en estado waiting. Puede que esté haciendo algo mal.

**Comment by AndriyHaydychuk** [comment]
Errores:
Failed to load resource: the server responded with a status of 404 (Not Found)
%7B%7Bs.Cover%7D%7D Failed to load resource: the server responded with a status of 404 (Not Found)
ionicons.woff Failed to load resource: the server responded with a status of 404 (Not Found)
ionicons.woff Failed to load resource: the server responded with a status of 404 (Not Found)
music.app.min.js:61 Uncaught ReferenceError: cordova is not defined
    at music.app.min.js:61
    at Array.<anonymous> (ionic.bundle.js:53329)
    at onPlatformReady (ionic.bundle.js:2491)
    at onWindowLoad (ionic.bundle.js:2472)
music.app.min.js:31 undefined
ionic.bundle.js:25642 TypeError: Cannot read property 'tintstatusbar' of undefined
    at music.app.min.js:46
    at processQueue (ionic.bundle.js:27879)
    at ionic.bundle.js:27895
    at Scope.$eval (ionic.bundle.js:29158)
    at Scope.$digest (ionic.bundle.js:28969)
    at ionic.bundle.js:29197
    at completeOutstandingRequest (ionic.bundle.js:18706)
    at ionic.bundle.js:18978

**Comment by AndriyHaydychuk** [comment]
Plugins instalados:
![plugins](https://cloud.githubusercontent.com/assets/26671628/24322396/ca9057a4-1163-11e7-9108-7c4dc96c6425.PNG)

**Comment by AndriyHaydychuk** [comment]
Despues de instalar los plugins, el problema persiste: 
![captura](https://cloud.githubusercontent.com/assets/26671628/24322420/6a2a7966-1164-11e7-8ce9-95998d3bffb8.PNG)

**Comment by cinder92** [comment]
El proyecto solo está disponible para android, puedes intentarlo en esa terminal?

**Comment by AndriyHaydychuk** [comment]
No he llegado a realizar un debut de la app por qué los errores no me
permiten hacerlo. De todas formas desde el navegador al ejecutar ionic
serve se queda en waiting y no pasa de allí. En github he publicado los
erres que me da la consola al intentar abrir la app. Perdona las molestias
y muchas gracias por ayudarme con esto.

**Comment by cinder92** [comment]
Lo que sucede es que utiliza modulos nativos hechos en Java para obtener las canciones del dispositivo, por eso es necesario que lo pruebes ya sea en el emulador o en una terminal real.
